# Site settings

baseurl: "" # the subpath of your site, e.g. /portfolio
url: "" # the base hostname & protocol for your site
language: "" # language to set into html tag, default is en

# User settings

author: Paulo Quicoli
author-title: Software Developer/Software Architect
gravatar: d36a082aacb53b6f76869748fb4b81d4
email: pauloquicoli@gmail.com
twitter: pauloquicoli
github: quicoli
googleplus: +PauloQuicoli
facebook: Paulo Quicoli
linkedin: pauloquicoli/en
bio: "Fast-learner, adaptable, motivated, committed and customer-oriented software developer with 15 years of experience in 
software analysis, architecture design, development and customer support. 
With an open-minded and sincere attitude, I am a collaborative team player in search of giving my best.
Post-graduated in Engineering and Software Architecture, graduated in Technology of Data Processing, 
English language level advanced (IELTS 6.5), certified Scrum Master, 
Lecturer in events: Embarcadero Conference and Firebird Developers Day"

# Skills
#
# I'll use five differents levels:
# 1 - Studying: You know the basics of the skill and is studying it to get better
# 2 - Padawan: You know a little more than the basics and is comfortable to work with it
# 3 - Work with: You know how to handle the skill and how to properly use it in a real project
# 4 - Specialist: You have advanced knowledge of the skill and know how to use its best practices in a real project
# 5 - Jedi: You master the skill, know how and when to use and when not use it
#
# You can change these names in _includes/_skill-level-name.html if you wish
#
# If you don't want one of the sections below, leave the variable without any values
front-end:
  - name: Windows Presentation Foundation (WPF)
    level:5
  - name: ASP.NET MVC
    level:4
  - name:
    level
  - name:
    level:
  - name: Angular
    level: 2
  - name:
    level:
  - name: Bootstrap
    level: 3
  - name: Materialize CSS
    level: 2
  - name: 
    level:
  - name:
    level:
  - name: 
    level:
  - name: 
    level:
  - name: 
    level:
  - name: 
    level:

back-end:
  - name: C#
    level: 4
  - name: Delphi
    level: 4
  - name:
    level:
  - name: 
    level:
  - name: 
    level:
  - name:
    level:
  - name: SQL
    level: 4
  - name: 
    level:

mobile:
  - name: Xamarin
    level: 3
  - name: Apache Cordova
    level: 3
  - name: Ionic
    level: 3
  - name: 
    level: 

db:
  - name: MySQL
    level: 3
  - name: PostgreSQL
    level: 2
  - name:
    level
  - name: SQL Server
    level: 3
  - name: Oracle
    level: 2
  - name: Firebird
    level: 4
  - name: NoSQL
    level: 1

devops:
  - name:
    level:
  - name: 
    level:
  - name:
    level:
  - name: Git
    level: 3
  - name:
    level:
  - name:
    level:
  - name:
    level:

methodologies:
  - name: Agile Methodologies
    level: 3
  - name: Scrum
    level: 4
  - name: 
    level:

others:
  - name: Web Services
    level: 4
  - name: WebAPI/REST
    level: 4
  - name: WCF
    level: 4
  - name: MVVM
    level: 4
  - name: nHibernate
    level: 4
  - name: Unit Tests (NUnit, DUnit)
    level: 3
  - name: Design Patterns
    level: 3
  - name: 
    level:
  - name:
    level:
  - name:
    level:
  - name:
    level:
  - name:
    level:
  - name:
    level:

# Build settings

markdown: kramdown
highlighter: rouge
sitemap: true # Generate sitemap.xml

sass:
  sass_dir: css
  style: compressed
## For more settings: https://jekyllrb.com/docs/configuration/

# exclude files if no need build
exclude: ['package.json', 'node_modules', 'README.md', 'LICENSE']

# Gems
gems: [jekyll-sitemap, bourbon]
